const $=s=>document.querySelector(s);
const weatherCodes={0:['Clear sky','☀️'],1:['Mainly clear','🌤️'],2:['Partly cloudy','⛅'],3:['Overcast','☁️'],45:['Foggy','🌫️'],48:['Icy fog','🌫️'],51:['Light drizzle','🌦️'],53:['Drizzle','🌦️'],55:['Heavy drizzle','🌧️'],61:['Light rain','🌦️'],63:['Rain','🌧️'],65:['Heavy rain','🌧️'],71:['Light snow','🌨️'],73:['Snow','🌨️'],75:['Heavy snow','❄️'],80:['Rain showers','🌦️'],81:['Rain showers','🌧️'],82:['Heavy showers','⛈️'],95:['Thunderstorm','⛈️']};
$('#today').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short'}).format(new Date());
function readCache(key,maxAge=86400000){try{const item=JSON.parse(localStorage.getItem(key));return item&&Date.now()-item.saved<maxAge?item.data:null}catch{return null}}
function writeCache(key,data){try{localStorage.setItem(key,JSON.stringify({saved:Date.now(),data}))}catch{}}
async function quickFetch(url,ms=6500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{signal:controller.signal})}finally{clearTimeout(timer)}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const timeFmt=new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}),dayFmt=new Intl.DateTimeFormat('en-GB',{weekday:'short'});
const compass=degrees=>['N','NE','E','SE','S','SW','W','NW'][Math.round(degrees/45)%8];
const weatherInfo=code=>weatherCodes[code]||['Changeable','🌤️'];
const weatherAt=(d,i)=>({time:d.hourly.time[i],temperature:d.hourly.temperature_2m[i],code:d.hourly.weather_code[i],rainChance:d.hourly.precipitation_probability[i]??0,rain:d.hourly.precipitation[i]??0,wind:d.hourly.wind_speed_10m[i],gust:d.hourly.wind_gusts_10m[i],direction:d.hourly.wind_direction_10m[i]});
function rainHeadline(hours){const wet=h=>h.rain>=.1||h.rainChance>=50;const firstWet=hours.findIndex(wet);if(firstWet===0){const dryIndex=hours.findIndex((h,i)=>i>0&&!wet(h));return dryIndex>0?`Rain easing around ${timeFmt.format(new Date(hours[dryIndex].time))}`:'Rain likely for the next few hours'}if(firstWet>0)return `Dry until ${timeFmt.format(new Date(hours[firstWet].time))}`;return 'No rain expected for the rest of the day'}
function hourlyMarkup(hours,markNow=false){return hours.map((h,i)=>{const info=weatherInfo(h.code);return `<div class="hour ${markNow&&i===0?'current-hour':''}"><small>${markNow&&i===0?'Now':timeFmt.format(new Date(h.time))}</small><span title="${info[0]}">${info[1]}</span><b>${Math.round(h.temperature)}°</b><em>● ${Math.round(h.rainChance)}%</em><i>${h.rain.toFixed(1)} mm</i></div>`}).join('')}
function dailyMarkup(d,start,count){return d.daily.time.slice(start,start+count).map((date,n)=>{const i=start+n,info=weatherInfo(d.daily.weather_code[i]);return `<div class="day"><small>${start===0&&n===0?'Today':dayFmt.format(new Date(date+'T12:00:00'))}</small><span>${info[1]}</span><b>${Math.round(d.daily.temperature_2m_max[i])}° <i>${Math.round(d.daily.temperature_2m_min[i])}°</i></b><em>● ${Math.round(d.daily.precipitation_probability_max[i]??0)}%</em></div>`}).join('')}
let weatherData=null,weatherTab='now';
function renderWeatherTab(){if(!weatherData)return;const d=weatherData,now=new Date(),today=d.daily.time[0],tomorrow=d.daily.time[1];const all=d.hourly.time.map((_,i)=>weatherAt(d,i));const futureToday=all.filter(h=>new Date(h.time)>=new Date(now.getFullYear(),now.getMonth(),now.getDate(),now.getHours())&&h.time.startsWith(today));const todayHours=all.filter(h=>h.time.startsWith(today));const tomorrowHours=all.filter(h=>h.time.startsWith(tomorrow));if(weatherTab==='week'){$('#weatherPanel').innerHTML=`<div class="daily-grid">${dailyMarkup(d,0,7)}</div>`;return}const hours=weatherTab==='tomorrow'?tomorrowHours:weatherTab==='today'?todayHours:futureToday;const lead=hours[0]||all[0],info=weatherInfo(weatherTab==='now'?d.current.weather_code:lead.code),temp=weatherTab==='now'?d.current.temperature_2m:lead.temperature,feels=weatherTab==='now'?d.current.apparent_temperature:null,wind=weatherTab==='now'?d.current.wind_speed_10m:lead.wind,gust=weatherTab==='now'?d.current.wind_gusts_10m:lead.gust,direction=weatherTab==='now'?d.current.wind_direction_10m:lead.direction;$('#weatherPanel').innerHTML=`<div class="weather-now"><div class="weather-primary"><strong id="temperature">${Math.round(temp)}°</strong><span id="weatherIcon" aria-hidden="true">${info[1]}</span><div><p id="condition">${info[0]}</p><small id="feelsLike">${feels==null?(weatherTab==='tomorrow'?'Tomorrow morning':'Hourly outlook'):`Feels like ${Math.round(feels)}°`}</small></div></div><div class="wind-now"><span id="windArrow" style="transform:rotate(${direction}deg)">↑</span><div><b id="windSpeed">${Math.round(wind)} mph</b><small id="windDetail">${compass(direction)} · gusts ${Math.round(gust)} mph</small></div></div></div><div class="rain-callout"><span>●</span><div><small>RAIN WINDOW</small><strong>${rainHeadline(hours)}</strong></div></div><div class="hourly-wrap"><div class="hourly">${hourlyMarkup(hours.slice(0,weatherTab==='now'?12:24),weatherTab==='now')}</div></div>`}
function showWeather(d,cached=false){weatherData=d;renderWeatherTab();$('#weatherStatus').innerHTML=`${cached?'Saved forecast · refreshing':'Updated '+timeFmt.format(new Date())} · <a href="https://open-meteo.com/" target="_blank" rel="noopener">Open-Meteo</a>`}
function seaState(height){if(height<.1)return'Calm';if(height<.5)return'Smooth';if(height<1.25)return'Slight';if(height<2.5)return'Moderate';if(height<4)return'Rough';return'Very rough'}
function showMarine(d){const i=Math.max(0,d.hourly.time.findIndex(t=>new Date(t)>=new Date())),height=d.hourly.wave_height[i],period=d.hourly.wave_period[i],direction=d.hourly.wave_direction[i],state=seaState(height);$('#seaSummary').textContent=`${height.toFixed(1)} m waves · ${state.toLowerCase()}`;$('#waveHeight').textContent=height.toFixed(1)+' m';$('#seaState').textContent=state;$('#waveDirection').textContent=compass(direction)+' '+Math.round(direction)+'°';$('#wavePeriod').textContent=period.toFixed(1)+' sec'}
async function loadMarine(){const cached=readCache('robbo-marine',10800000);if(cached)showMarine(cached);try{const r=await quickFetch('https://marine-api.open-meteo.com/v1/marine?latitude=52.95&longitude=1.32&hourly=wave_height,wave_direction,wave_period&timezone=Europe%2FLondon&forecast_days=2',8000);if(!r.ok)throw 0;const d=await r.json();showMarine(d);writeCache('robbo-marine',d)}catch{if(!cached)$('#seaSummary').textContent='Sea forecast unavailable'}}
async function loadWeather(){const cached=readCache('robbo-weather-v3',10800000);if(cached)showWeather(cached,true);try{const params='latitude=52.9312&longitude=1.3010&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m&hourly=temperature_2m,weather_code,precipitation_probability,precipitation,wind_speed_10m,wind_gusts_10m,wind_direction_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&wind_speed_unit=mph&timezone=Europe%2FLondon&forecast_days=7';const r=await quickFetch('https://api.open-meteo.com/v1/forecast?'+params,8000);if(!r.ok)throw 0;const d=await r.json();showWeather(d);writeCache('robbo-weather-v3',d)}catch{if(!cached){$('#condition').textContent='Weather unavailable';$('#weatherStatus').textContent='Could not refresh · tap to retry';$('#weatherStatus').onclick=loadWeather}else $('#weatherStatus').textContent='Saved forecast · currently offline'}loadMarine()}
document.querySelectorAll('[data-weather-tab]').forEach(button=>button.addEventListener('click',()=>{weatherTab=button.dataset.weatherTab;document.querySelectorAll('[data-weather-tab]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-selected',active)});renderWeatherTab()}));
const feeds=[['🇬🇧','UK','https://feeds.bbci.co.uk/news/uk/rss.xml'],['💼','Business','https://feeds.bbci.co.uk/news/business/rss.xml'],['🏠','Property','https://news.google.com/rss/search?q=UK+property+market&hl=en-GB&gl=GB&ceid=GB:en'],['🌍','World','https://feeds.bbci.co.uk/news/world/rss.xml']];
async function fetchFeed([icon,label,url]){const r=await quickFetch('https://api.rss2json.com/v1/api.json?rss_url='+encodeURIComponent(url),7000);if(!r.ok)throw 0;const d=await r.json(),item=d.items?.[0];if(!item)throw 0;return{icon,label,title:item.title,link:item.link}}
function showNews(items,status){$('#newsList').innerHTML=items.map(n=>`<a class="news-item" href="${n.link}" target="_blank" rel="noopener"><span class="news-icon">${n.icon}</span><span><b>${escapeHtml(n.title)}</b><small>${n.label}</small></span><em>›</em></a>`).join('');$('#newsStatus').textContent=status}
let newsLoaded=false;async function loadNews(force=false){if(newsLoaded&&!force)return;newsLoaded=true;const cached=readCache('robbo-news',21600000);if(cached)showNews(cached,'Saved briefing · refreshing');else $('#newsList').innerHTML='<p class="loading">Gathering today’s headlines…</p>';const results=await Promise.allSettled(feeds.map(fetchFeed)),items=results.filter(x=>x.status==='fulfilled').map(x=>x.value);if(items.length){showNews(items,'Updated '+new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date()));writeCache('robbo-news',items)}else if(!cached)showNews(feeds.map(([icon,label,url])=>({icon,label,title:`Open today’s ${label.toLowerCase()} headlines`,link:url})),'Source links available · tap to open')}
$('#refreshNews').addEventListener('click',()=>{newsLoaded=false;loadNews(true)});
function loadMarkets(){const host=$('#marketStrip');if(host.dataset.loaded)return;host.dataset.loaded='true';host.innerHTML='<div class="tradingview-widget-container__widget"></div>';const script=document.createElement('script');script.src='https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js';script.async=true;script.textContent=JSON.stringify({symbols:[{proName:'NASDAQ:RKLB',title:'RKLB'},{proName:'NYSE:BBAI',title:'BBAI'},{proName:'NYSE:CCJ',title:'CCJ'}],showSymbolLogo:false,isTransparent:true,displayMode:'compact',colorTheme:'light',locale:'en'});host.appendChild(script)}
let tasks=[];try{tasks=JSON.parse(localStorage.getItem('robbo-tasks-v2'))||[]}catch{}
function saveTasks(){localStorage.setItem('robbo-tasks-v2',JSON.stringify(tasks));renderTasks()}
function renderTasks(){const open=tasks.filter(t=>!t.done).length;$('#taskCount').textContent=open+' open';$('#emptyTasks').hidden=tasks.length>0;$('#taskList').innerHTML=tasks.map(t=>`<li class="task ${t.done?'done':''}" data-id="${t.id}"><input type="checkbox" ${t.done?'checked':''} aria-label="Complete action"><label><small>${escapeHtml(t.project||'Personal')}</small>${escapeHtml(t.text)}</label><button aria-label="Delete action">×</button></li>`).join('')}
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#taskInput'),text=input.value.trim(),project=$('#taskProject').value;if(!text)return;tasks.unshift({id:Date.now(),project,text,done:false});input.value='';saveTasks()});
$('#taskList').addEventListener('click',e=>{const li=e.target.closest('.task');if(!li)return;const id=Number(li.dataset.id),idx=tasks.findIndex(t=>t.id===id);if(e.target.matches('button'))tasks.splice(idx,1);else if(e.target.matches('input'))tasks[idx].done=e.target.checked;saveTasks()});
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{$('#taskProject').value=button.dataset.project;$('#tasks').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#taskInput').focus(),350)}));
const practicalOutlooks=[
  ['Protect your attention today. One useful decision on a live project is worth more than clearing ten easy distractions.','Choose the move that creates momentum.'],
  ['A conversation you have been circling will improve once the numbers are on the table. Be fair, but do not dilute your position just to keep things comfortable.','Say what matters plainly.'],
  ['Your instinct for balance is useful, provided it does not become delay. Set the downside, decide what good looks like, then make the call.','Define the risk and decide.'],
  ['Today favours refinement over reinvention. Tighten the offer, improve the presentation and finish the piece already closest to earning attention.','Finish before starting again.'],
  ['There is value in your network today, but only if you make the first move. A short, specific message will work better than waiting for the perfect introduction.','Make one useful contact.'],
  ['Keep the commercial test simple: does this move create cash, reduce risk or build a valuable relationship? If not, it can wait.','Prioritise measurable value.'],
  ['Step back before agreeing to anything that adds work without a clear return. Good judgement today looks like a calm no as often as an enthusiastic yes.','Protect time and margin.']
];
const outlook=practicalOutlooks[Math.floor(Date.now()/86400000)%practicalOutlooks.length];$('#outlookText').textContent=outlook[0];$('#outlookAction').textContent=outlook[1];
renderTasks();loadWeather();
const observe=(selector,fn)=>{const el=$(selector);if(!('IntersectionObserver'in window)){fn();return}const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){fn();observer.disconnect()}},{rootMargin:'300px'});observer.observe(el)};
observe('#portfolio',loadMarkets);observe('#briefing',loadNews);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
