const $=s=>document.querySelector(s);
const weatherCodes={0:['Clear sky','☀️'],1:['Mainly clear','🌤️'],2:['Partly cloudy','⛅'],3:['Overcast','☁️'],45:['Foggy','🌫️'],48:['Icy fog','🌫️'],51:['Light drizzle','🌦️'],53:['Drizzle','🌦️'],55:['Heavy drizzle','🌧️'],61:['Light rain','🌦️'],63:['Rain','🌧️'],65:['Heavy rain','🌧️'],71:['Light snow','🌨️'],73:['Snow','🌨️'],75:['Heavy snow','❄️'],80:['Rain showers','🌦️'],81:['Rain showers','🌧️'],82:['Heavy showers','⛈️'],95:['Thunderstorm','⛈️']};
$('#today').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short'}).format(new Date());
function readCache(key,maxAge=86400000){try{const item=JSON.parse(localStorage.getItem(key));return item&&Date.now()-item.saved<maxAge?item.data:null}catch{return null}}
function writeCache(key,data){try{localStorage.setItem(key,JSON.stringify({saved:Date.now(),data}))}catch{}}
async function quickFetch(url,ms=6500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{signal:controller.signal})}finally{clearTimeout(timer)}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showWeather(d,cached=false){const current=d.current,info=weatherCodes[current.weather_code]||['Cromer weather','🌤️'];$('#temperature').textContent=Math.round(current.temperature_2m)+'°';$('#condition').textContent=info[0];$('#weatherIcon').textContent=info[1];$('#feelsLike').textContent='Feels like '+Math.round(current.apparent_temperature)+'°';$('#forecast').innerHTML=d.daily.time.slice(1,4).map((date,i)=>{const idx=i+1,wi=weatherCodes[d.daily.weather_code[idx]]||['','🌤️'];return `<div><small>${new Intl.DateTimeFormat('en-GB',{weekday:'short'}).format(new Date(date+'T12:00:00'))}</small><span>${wi[1]}</span><b>${Math.round(d.daily.temperature_2m_max[idx])}° <i>${Math.round(d.daily.temperature_2m_min[idx])}°</i></b></div>`}).join('');$('#weatherStatus').textContent=(cached?'Saved forecast · refreshing':'Live weather')+' · Open-Meteo'}
async function loadWeather(){const cached=readCache('robbo-weather',10800000);if(cached)showWeather(cached,true);try{const url='https://api.open-meteo.com/v1/forecast?latitude=52.9312&longitude=1.3010&current=temperature_2m,apparent_temperature,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=Europe%2FLondon&forecast_days=4';const r=await quickFetch(url);if(!r.ok)throw 0;const d=await r.json();showWeather(d);writeCache('robbo-weather',d)}catch{if(!cached){$('#condition').textContent='Weather unavailable';$('#weatherStatus').textContent='Could not refresh · tap to retry';$('#weatherStatus').onclick=loadWeather}else $('#weatherStatus').textContent='Saved forecast · currently offline'}}
const horoscopeFallback=['Balance comes from choosing what deserves your energy. A clear conversation could untangle something that has felt more complicated than it really is.','Your instinct for harmony is useful today, but do not smooth over your own priorities. One thoughtful decision will create welcome momentum.','A fresh perspective arrives when you leave a little space in the day. Trust your eye for what feels right, then take one practical step toward it.'];
function showHoroscope(text,source){$('#horoscopeText').textContent=text;$('#horoscopeSource').textContent=source}
async function loadHoroscope(){const cached=readCache('robbo-horoscope',43200000);if(cached)showHoroscope(cached,'Saved daily reading · refreshing');else showHoroscope(horoscopeFallback[new Date().getDate()%3],'Today’s Libra reading');try{const r=await quickFetch('https://api.allorigins.win/raw?url='+encodeURIComponent('https://ohmanda.com/api/horoscope/libra/'));if(!r.ok)throw 0;const d=await r.json(),text=d.horoscope||d.description;if(text){showHoroscope(text,'Live daily reading · Ohmanda');writeCache('robbo-horoscope',text)}}catch{if(cached)showHoroscope(cached,'Saved daily reading')}}
const feeds=[['🇬🇧','UK','https://feeds.bbci.co.uk/news/uk/rss.xml'],['💼','Business','https://feeds.bbci.co.uk/news/business/rss.xml'],['🏠','Property','https://news.google.com/rss/search?q=UK+property+market&hl=en-GB&gl=GB&ceid=GB:en'],['🌍','World','https://feeds.bbci.co.uk/news/world/rss.xml']];
async function fetchFeed([icon,label,url]){const r=await quickFetch('https://api.rss2json.com/v1/api.json?rss_url='+encodeURIComponent(url),7000);if(!r.ok)throw 0;const d=await r.json(),item=d.items?.[0];if(!item)throw 0;return{icon,label,title:item.title,link:item.link}}
function showNews(items,status){$('#newsList').innerHTML=items.map(n=>`<a class="news-item" href="${n.link}" target="_blank" rel="noopener"><span class="news-icon">${n.icon}</span><span><b>${escapeHtml(n.title)}</b><small>${n.label}</small></span><em>›</em></a>`).join('');$('#newsStatus').textContent=status}
let newsLoaded=false;async function loadNews(force=false){if(newsLoaded&&!force)return;newsLoaded=true;const cached=readCache('robbo-news',21600000);if(cached)showNews(cached,'Saved briefing · refreshing');else $('#newsList').innerHTML='<p class="loading">Gathering today’s headlines…</p>';const results=await Promise.allSettled(feeds.map(fetchFeed)),items=results.filter(x=>x.status==='fulfilled').map(x=>x.value);if(items.length){showNews(items,'Updated '+new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date()));writeCache('robbo-news',items)}else if(!cached)showNews(feeds.map(([icon,label,url])=>({icon,label,title:`Open today’s ${label.toLowerCase()} headlines`,link:url})),'Source links available · tap to open')}
$('#refreshNews').addEventListener('click',()=>{newsLoaded=false;loadNews(true)});
function loadMarkets(){const host=$('#marketStrip');if(host.dataset.loaded)return;host.dataset.loaded='true';host.innerHTML='<div class="tradingview-widget-container__widget"></div>';const script=document.createElement('script');script.src='https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js';script.async=true;script.textContent=JSON.stringify({symbols:[{proName:'NYSE:IONQ',title:'IONQ'},{proName:'NASDAQ:RKLB',title:'RKLB'},{proName:'NASDAQ:RGTI',title:'RGTI'}],showSymbolLogo:false,isTransparent:true,displayMode:'compact',colorTheme:'dark',locale:'en'});host.appendChild(script)}
let tasks=[];try{tasks=JSON.parse(localStorage.getItem('robbo-tasks-v2'))||[]}catch{}
function saveTasks(){localStorage.setItem('robbo-tasks-v2',JSON.stringify(tasks));renderTasks()}
function renderTasks(){const open=tasks.filter(t=>!t.done).length;$('#taskCount').textContent=open+' left';$('#emptyTasks').hidden=tasks.length>0;$('#taskList').innerHTML=tasks.map(t=>`<li class="task ${t.done?'done':''}" data-id="${t.id}"><input type="checkbox" ${t.done?'checked':''} aria-label="Complete task"><label>${escapeHtml(t.text)}</label><button aria-label="Delete task">×</button></li>`).join('')}
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#taskInput'),text=input.value.trim();if(!text)return;tasks.unshift({id:Date.now(),text,done:false});input.value='';saveTasks()});
$('#taskList').addEventListener('click',e=>{const li=e.target.closest('.task');if(!li)return;const id=Number(li.dataset.id),idx=tasks.findIndex(t=>t.id===id);if(e.target.matches('button'))tasks.splice(idx,1);else if(e.target.matches('input'))tasks[idx].done=e.target.checked;saveTasks()});
renderTasks();loadWeather();
const observe=(selector,fn)=>{const el=$(selector);if(!('IntersectionObserver'in window)){fn();return}const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){fn();observer.disconnect()}},{rootMargin:'300px'});observer.observe(el)};
observe('#portfolio',loadMarkets);observe('#horoscope',loadHoroscope);observe('#briefing',loadNews);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
